warp_mesh = "morph.bsm2"
shadowmap_size = 512

draw_order = ["retouch","ears","mustache"]

[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
samplers = { selection_tex="redmask_new_3.png", lookupTexTeeth="teeth_highlighter5.png", lookupTexEyes="lut_80_percent.png", tex_highlight="FLARE_39_512.png", tex_softLight="soft.png", tex_normalMakeup="80s_256.png"}

[materials.ears]
vs = "vertex.vert"
fs = "pbr_hdr.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = true
shadow = true
# samplers = { tex = "minnie_mouse_BaseColor.png" }
[materials.ears.samplers]
tex_diffuse="minnie_mouse_BaseColor.png"
tex_normal="minnie_mouse_Normal.png"
tex_metallic="minnie_mouse_Metallic.png"
tex_roughness="minnie_mouse_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

[materials.mustache]
vs = "billboard.vert"
fs = "tex.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = true
shadow = true
samplers = { tex = "minnie_mouse_BaseColor.png" }

