warp_mesh = "face.bsm2"
msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', '!glfx_WARP_IMAGE', 'facemat', 'Mask_mat', 'Brilliant_mat', 'Metal_mat', 'Pattern_mat']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
lookupTexTeeth="lut3d_TEETH_medium.png"
lookupTexEyes="lut3d_EYES_medium.png"
tex_softLight="FemaleNightMask_soft.png"
tex_normalMakeup="FemaleNightMask_makeup.png"
tex_highlight="FLARE_40_512.png"

# Cut
[materials.facemat]
vs = "facemat.vert"
fs = "facemat.frag"
blend = "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = false
samplers = {}

# PBR
[materials.Mask_mat]
vs = "mask_mat.vert"
fs = "mask_mat.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.Mask_mat.samplers]
tex_diffuse="Mask_mat_Base_Color.png"
tex_metallic="Mask_mat_Metallic.png"
tex_roughness="Mask_mat_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

# PBR
[materials.Brilliant_mat]
vs = "mat_crystal.vert"
fs = "face.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.Brilliant_mat.samplers]
tex_diffuse="Brilliant_mat_Base_Color.ktx"
tex_normal="Brilliant_mat_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="Brilliant_mat_MRAO.ktx"
tex_skybox="cubemap.ktx"

# PBR
[materials.Metal_mat]
vs = "metal_mat.vert"
fs = "metal_mat.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.Metal_mat.samplers]
tex_diffuse="Metal_mat_Base_Color.png"
tex_metallic="Metal_mat_Metallic.png"
tex_roughness="Metal_mat_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

# PBR
[materials.Pattern_mat]
vs = "pattern_mat.vert"
fs = "pattern_mat.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = true
colorwrite = true
zwrite = true
shadow = false
[materials.Pattern_mat.samplers]
tex_diffuse="Mask_mat_Base_Color.png"
tex_metallic="Mask_mat_Metallic.png"
tex_roughness="Mask_mat_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
