warp_mesh = "face.bsm2"
msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['!glfx_WARP_IMAGE', 'TriMat', '!glfx_UPDATE_BG', 'retouch', 'mesh',  'morph',   'glass']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
lookupTexTeeth="lut3d_TEETH_medium.png"
lookupTexEyes="lut3d_EYES_medium.png"
tex_softLight="soft_princess_256.png"
tex_normalMakeup="face_shadow_BaseColor.png"

# Cut
[materials.morph]
vs = "morph.vert"
fs = "morph.frag"
blend = "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = false
samplers = {}

# PBR
[materials.mesh]
vs = "mesh.vert"
fs = "mesh.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.mesh.samplers]
tex_diffuse="mesh_BaseColor.png"
tex_normal="mesh_Normal.png"
tex_metallic="mesh_Metallic.png"
tex_roughness="mesh_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

# PBR
[materials.glass]
vs = "glass.vert"
fs = "glass.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.glass.samplers]
tex_diffuse="mesh_BaseColor.png"
tex_normal="mesh_Normal.png"
tex_metallic="mesh_Metallic.png"
tex_roughness="mesh_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_skybox="skybox.ktx"

[materials.TriMat]
vs = "fstri.vert"
fs = "lut.frag"
blend = "off"
backfaces = true
shadow = false
zwrite = false
samplers = {}
