msaa = 1
draw_order = ["retouch","!glfx_FACE_Z","ear","ear_hair","ear01","ear_hair01","nose","nose_base","nose_hair","tongue"]

[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
samplers = { selection_tex="redmasksuperpuperbest.png", lookupTexTeeth="teeth_highlighter5.png", lookupTexEyes="lut_80_percent.png"}


[materials.ear]
vs = "vertex.vert"
fs = "pbr.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
samplers = { tex_diffuse="ear_Base_Color.ktx", tex_normal="ear_Normal.ktx", tex_metallic="zero.ktx", tex_roughness="ear_Roughness.ktx" }

[materials.ear_hair]
vs = "vertex.vert"
fs = "pbr2sided.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = true
colorwrite = true
zwrite = true
shadow = false
samplers = { tex_diffuse="ear_hair_Base_Color.ktx", tex_normal="normal.ktx", tex_metallic="zero.ktx", tex_roughness="ear_hair_Roughness.ktx" }

[materials.ear01]
vs = "vertex_dyn.vert"
fs = "pbr.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
samplers = { tex_diffuse="ear_Base_Color.ktx", tex_normal="ear_Normal.ktx", tex_metallic="zero.ktx", tex_roughness="ear_Roughness.ktx" }

[materials.ear_hair01]
vs = "vertex_dyn.vert"
fs = "pbr2sided.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = true
colorwrite = true
zwrite = true
shadow = false
samplers = { tex_diffuse="ear_hair_Base_Color.ktx", tex_normal="normal.ktx", tex_metallic="zero.ktx", tex_roughness="ear_hair_Roughness.ktx" }

[materials.nose]
vs = "vertex.vert"
fs = "pbr.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
samplers = { tex_diffuse="nose_Base_Color.ktx", tex_normal="nose_Normal.ktx", tex_metallic="nose_Metallic.ktx", tex_roughness="nose_Roughness.ktx" }

[materials.nose_base]
vs = "vertex.vert"
fs = "pbr.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
samplers = { tex_diffuse="nose_base_Base_Color.ktx", tex_normal="nose_base_Normal.ktx", tex_metallic="zero.ktx", tex_roughness="nose_base_Roughness.ktx" }

[materials.nose_hair]
vs = "vertex.vert"
fs = "pbr2sided.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = true
colorwrite = true
zwrite = true
shadow = false
samplers = { tex_diffuse="nose_hair_Base_Color.ktx", tex_normal="nose_hair_Normal.ktx", tex_metallic="zero.ktx", tex_roughness="nose_hair_Roughness.ktx" }

[materials.tongue]
vs = "vertex.vert"
fs = "pbr.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
samplers = { tex_diffuse="tongue_Base_Color.ktx", tex_normal="tongue_Normal.ktx", tex_metallic="tongue_Metallic.ktx", tex_roughness="tongue_Roughness.ktx" }

