warp_mesh = "Snap.bsm2"
msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', '!glfx_WARP_IMAGE', '!glfx_FACE_MOUTH_Z', 'cut', 'lemon', 'lemon_glass', 'video']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
selection_tex="REDMASK_v3_256.png"
lookupTexTeeth="TEETH_medium.png"
tex_softLight="SOFT_princess_256.png"
tex_normalMakeup="lashes7.png"
tex_highlight="FLARE_38_768.png"

# Cut
[materials.cut]
vs = "cut.vert"
fs = "cut.frag"
blend = "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = false
samplers = {}

# PBR
[materials.lemon]
vs = "lemon.vert"
fs = "lemon.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.lemon.samplers]
tex_diffuse="lemon_Base_Color.ktx"
tex_normal="lemon_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="lemon_MRAO.ktx"

# PBR
[materials.lemon_glass]
vs = "lemon.vert"
fs = "lemon.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.lemon_glass.samplers]
tex_diffuse="glasses_Base_Color.ktx"
tex_normal="glasses_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="glasses_MRAO.ktx"

# PBR
[materials.video]
vs = "lemon.vert"
fs = "video_a.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = false
shadow = false
samplers = {}
