warp_mesh = "Trollson_morphing.bsm2"
msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', '!glfx_WARP_IMAGE', 'facemat', 'hair_opacity', 'glasses']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
selection_tex="REDMASK_v3_256.png"
lookupTexTeeth="TEETH_medium.png"
lookupTexEyes="EYES_medium.png"
tex_softLight="soft_doll_512.png"
tex_normalMakeup="facemat_Base_Color.ktx"
tex_highlight="FLARE_39_512.png"

# Cut
[materials.facemat]
vs = "facemat.vert"
fs = "facemat.frag"
blend = "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = false
samplers = {}

# PBR
[materials.hair_opacity]
vs = "hair_opacity.vert"
fs = "hair_opacity.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = true
colorwrite = true
zwrite = true
shadow = false
[materials.hair_opacity.samplers]
tex_diffuse="grandson_Base_Color.ktx"
tex_normal="grandson_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="grandson_MRAO.ktx"

# PBR
[materials.glasses]
vs = "glasses.vert"
fs = "glasses.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.glasses.samplers]
tex_diffuse="grandson_Base_Color.ktx"
tex_normal="grandson_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="grandson_MRAO.ktx"
