warp_mesh = "morph.bsm2"
msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', '!glfx_WARP_IMAGE', 'Morph', 'Mouse_ears_mat', 'Bow_mat', 'Mustache_mat', 'Nose_mat', 'Brilliant_mat']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
lookupTexTeeth="lut3d_TEETH_medium.png"
lookupTexEyes="lut3d_EYES_medium.png"
tex_softLight="MinnieMouse2_soft.png"
tex_normalMakeup="MinnieMouse2_makeup.png"
tex_highlight="FLARE_38_512.png"

# Cut
[materials.Morph]
vs = "morph.vert"
fs = "morph.frag"
blend = "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = false
samplers = {}

# PBR
[materials.Mouse_ears_mat]
vs = "mouse_ears_mat.vert"
fs = "mouse_ears_mat.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.Mouse_ears_mat.samplers]
tex_diffuse="Mouse_ears_mat_Base_Color.png"
tex_normal="Mouse_ears_mat_Normal.png"
tex_metallic="Mouse_ears_mat_Metallic.png"
tex_roughness="Mouse_ears_mat_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

# PBR
[materials.Bow_mat]
vs = "bow_mat.vert"
fs = "bow_mat.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = true
colorwrite = true
zwrite = true
shadow = false
[materials.Bow_mat.samplers]
tex_diffuse="Bow_mat_Base_Color.png"
tex_normal="Bow_mat_Normal.png"
tex_metallic="Bow_mat_Metallic.png"
tex_roughness="Bow_mat_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

# PBR
[materials.Mustache_mat]
vs = "mustache_mat.vert"
fs = "mustache_mat.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.Mustache_mat.samplers]
tex_diffuse="rabbit.png"
tex_metallic="Mustache_mat_Metallic.png"
tex_roughness="Mustache_mat_Roughness.png"

# PBR
[materials.Nose_mat]
vs = "nose_mat.vert"
fs = "nose_mat.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.Nose_mat.samplers]
tex_diffuse="rabbit.png"
tex_metallic="Mustache_mat_Metallic.png"
tex_roughness="Mustache_mat_Roughness.png"

# PBR
[materials.Brilliant_mat]
vs = "mat_crystal.vert"
fs = "face.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.Brilliant_mat.samplers]
tex_diffuse="Brilliant_mat_Base_Color.ktx"
tex_normal="Brilliant_mat_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="Brilliant_mat_MRAO.ktx"
tex_skybox="cubemap.ktx"
