shadowmap_size = 512

draw_order = ["eye","tongue","mouth","face"]

[materials.eye]
vs = "vertex.vert"
fs = "pbr.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = true
shadow = true
samplers = { tex_diffuse="eye_texture_diff.ktx" }

[materials.tongue]
vs = "vertex.vert"
fs = "pbr.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = true
shadow = true
samplers = { tex_diffuse="dog_tongue.ktx" }

[materials.face]
vs = "morphed.vert"
fs = "morphed.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = true
shadow = true
samplers = {}

[materials.mouth]
vs = "vertex.vert"
fs = "inside.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = true
shadow = true
samplers = { tex_diffuse="mouth.ktx" }
